# Brewfile
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/cask-fonts"

# The usual stuff
brew "coreutils"
brew "ffmpeg"
brew "grip"
brew "openconnect" #  anyconnect alternative for school vpn
brew "speedtest"
brew "python"
brew "tty-clock"
brew "neofetch"  # fucking ricers dude
brew "pfetch" # omg just stop
brew "stow"
brew "tmux"
brew "youtube-dl"
brew "starship"
brew "llvm"
brew "svn"
brew "git"
brew "vim"

# Casks
cask "alfred"
cask "discord"
cask "firefox"
cask "karabiner-elements"
cask "spotify"
cask "visual-studio-code"
cask "zoom"
cask "monitorcontrol"
cask "vlc"
cask "font-fira-code-nerd-font"
cask "basictex"
cask "obs"
# cask "adobe-creative-cloud" # actual bloat, only install if needed
cask "teamviewer"
